on: [push, pull_request]

jobs:

  test:

    name: ${{ matrix.lisp }}

    strategy:
      matrix:
        lisp: [sbcl, ecl]
    runs-on: ubuntu-20.04

    steps:

    - uses: actions/checkout@v2

    - name: Update $PATH
      run: |
        echo $PATH
        echo "PATH=$HOME/bin:$PATH" >> $GITHUB_ENV
    - name: Check $PATH
      run: echo $PATH

    - name: Download implementation
      env:
        LISP: ${{ matrix.lisp }}
      run: |
        pwd
        ls -l
        bash <(curl -s https://raw.githubusercontent.com/digikar99/lisp-travis-lite/master/run.sh)

    - name: Install digikar99/specialized-array-dispatch
      run: |
        mkdir -p ~/quicklisp/dists/digikar99
        ls -l ~/quicklisp/dists

    - name: Compile Tests
      run: cl --eval '(progn
                 (defun ql-dist::dist-name-pathname (name)
                   "Return the pathname that would be used for an installed dist with
                    the given NAME."
                  (ql-dist::qmerge
                   (make-pathname :directory (list* :relative "dists"
                                                    (uiop:split-string name :separator "/")))))
                 (defun digikar99-dist-enumeration-function ()
                   "The default function used for producing a list of dist objects."
                   (loop for file
                       in (directory (ql-dist::qmerge "dists/digikar99/*/distinfo.txt"))
                     collect (ql-dist::make-dist-from-file file)))
                 (push (quote digikar99-dist-enumeration-function)
                       ql::*dist-enumeration-functions*)
                 (ql-dist:install-dist
                  "http://dist.ultralisp.org/digikar99/specialized-array-dispatch.txt"
                  :prompt nil)
                 (push :travis *features*)
                 (push "~/" ql:*local-project-directories*)
                 (print ql:*local-project-directories*)
                 (print (ql:where-is-system "polymorphic-functions"))
                 (ql:quickload "polymorphic-functions")
                 (uiop:quit 0))'

    # Testing it on the second load confirms that functionalities do not
    # solely eval-when compile-toplevel, and that they persist across multiple loads.
    - name: Run Tests
      run: cl --eval '(progn
                 (defun ql-dist::dist-name-pathname (name)
                   "Return the pathname that would be used for an installed dist with
                    the given NAME."
                  (ql-dist::qmerge
                   (make-pathname :directory (list* :relative "dists"
                                                    (uiop:split-string name :separator "/")))))
                 (defun digikar99-dist-enumeration-function ()
                   "The default function used for producing a list of dist objects."
                   (loop for file
                       in (directory (ql-dist::qmerge "dists/digikar99/*/distinfo.txt"))
                     collect (ql-dist::make-dist-from-file file)))
                 (push (quote digikar99-dist-enumeration-function)
                       ql::*dist-enumeration-functions*)
                 (push "~/" ql:*local-project-directories*)
                 (push :travis *features*)
                 (ql:quickload "polymorphic-functions")
                 (asdf:test-system :polymorphic-functions)
                 (uiop:quit 0))'

